beam:
  admin:
    swagger-open: true  #是否开启swagger (true/false)
    kaptcha-open: false
    redis-open: false  # 是否开启redis缓存  true开启   false关闭
    shiro-redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
    version: 0.0.1
server:
   port: 8080
   servlet:
     context-path: /beam_ht
spring:
  profiles:
    active: @spring.active@


log:
  path: beam-admin-logs
---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/deam?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: deam
    password: 123456
    filters: log4j,wall,mergeStat
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000ms

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）

---


spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms  # 连接超时时长（毫秒）